name: Test redirects
on:
  push:
    branches: [ main ]
  # schedule:
  # - cron: '0 4 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/redirects-*.cy.js
